channels:
  - conda-forge
  - pypi
dependencies:
  - python==3.9.7
  - python-dotenv=0.15.0
  - marshmallow=3.10.0
  - pip
  - pip:
      - gunicorn==20.0.4
      - nauron==1.2
      - estnltk_core==1.7.2
      - stanza==1.5.0
      - torch
      - regex
      - networkx
      - gensim
      - numpy
      - packaging
      - pandas
      - scikit-learn
      - scipy
      - xgboost
      - nauron==1.2